apiVersion: v1
kind: Service
metadata:
  name: insurance-itau-service
spec:
  selector:
    app: insurance-itau
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer # Ou NodePort, ClusterIP