package itau.cotacao.seguro.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;
import java.util.UUID;

@Data
@DynamoDBTable(tableName = "Quote")
public class QuoteEntity {

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private Long idQuery;

    @DynamoDBAttribute
    private Long insurancePolicyId;

    @DynamoDBAttribute
    private UUID productId;

    @DynamoDBAttribute
    private UUID offerId;

    @DynamoDBAttribute
    private String category;

    @DynamoDBAttribute
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
    private LocalDateTime createdAt;

    @DynamoDBAttribute
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
    private LocalDateTime updatedAt;

    @DynamoDBAttribute
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.N)
    private BigDecimal totalMonthlyPremiumAmount;

    @DynamoDBAttribute
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.N)
    private BigDecimal totalCoverageAmount;

    @DynamoDBAttribute
    private Map<String, BigDecimal> coverages;

    @DynamoDBAttribute
    private List<String> assistances;

    @DynamoDBAttribute
    private CustomerEntity customer;
}